### ISSUE TITLE
CLI Common Issue Workaround

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#130]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by wangzelin007** [comment]
Debian sid workaround
```
sudo apt remove azure-cli -y && sudo apt autoremove -y
sudo rm -fr sudo rm -fr /etc/apt/sources.list.d/zure-cli.list

echo 'Package: azure-cli
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001'        | sudo tee /etc/apt/preferences.d/azure-cli

sudo apt update & sudo apt install azure-cli
```

**Comment by wangzelin007** [comment]
## Symptom

We have a centralized location to define API versions for each resource provider:

https://github.com/Azure/azure-cli/blob/daa568579dbaec5af1ac92d261014cf9ce3ff9b1/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L154-L158

Azure CLI supports 4 clouds, including 3 sovereign clouds:

- `AzureCloud`
- `AzureChinaCloud`
- `AzureUSGovernment`
- `AzureGermanCloud`

All of them use the same `latest` profile and the same API version for each resource provider.

However, it happens frequently that a new API version is only deployed to `AzureCloud`, but not other clouds. Using Azure CLI to call that API version leads to error like:

> NoRegisteredProviderFound - No registered resource provider found for location 'chinanorth' and API version '2019-06-15-preview' for type 'profiles/endpoints'. The supported api-versions are '2015-06-01, 2016-04-02, 2016-10-02, 2017-04-02, 2017-10-12, 2018-04-02, 2019-04-15'. The supported locations are 'chinanorth, chinanorth2, chinaeast, chinaeast2'.

## Temporary workaroud

Install previous versions of Azure CLI that use old API versions in sovereign clouds. The installation document has detailed instruction on how to install previous versions: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli

## Solution

Service team _should_ deploy the new API version to all clouds synchronously.

**Comment by wangzelin007** [comment]
## Questions

- Have you copied `~/.azure` folder from another computer or mounted it into a container?
- Could you share the detailed steps you followed to trigger this error?

## Workaround

First, you may try to clear the credential cache and re-login:

```
az account clear
az login
```

If this still doesn't help, you may temporarily turn off token cache encryption. (⚠ This is an internal experimental config option. We may change it or drop it anytime.)

```sh
az config set core.encrypt_token_cache=false
az login
```

**Comment by wangzelin007** [comment]
Yes, I can reproduce the problem and a fix/workaround:
1/ Delete the group "cloud-shell-storage-westeurope" in which the "Storage account" for the Cloud Shell has been created.
2/ Wait for the deletion.
3/ Go back to Cloud Shell and click "Create storage".
4/ See the issue by typing (for instance):

```text
$ echo "hello world" > ~/test.txt
bash: /home/benoit/test.txt: Read-only file system
```

5/ **Restart Cloud Shell with the "power" button/icon.**
6/ Check that the issue is fixed by typing (for instance):

```text
$ echo "hello world" > ~/test.txt
```

Hope this help.

**Comment by wangzelin007** [comment]
## How to tell if the installed Azure CLI is unofficial

**An unofficial Azure CLI has `dist-packages` in its call stack** (https://github.com/Azure/azure-cli/issues/22546):

```
The command failed with an unexpected error. Here is the traceback:
'RoleDefinitionsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 49, in list_role_definitions
    definitions_client.config.subscription_id)
AttributeError: 'RoleDefinitionsOperations' object has no attribute 'config'
```

`dist-packages` is Ubuntu Python's equivalent location of the official Python's `site-packages`.

The official Azure CLI's `site-packages` is at

```
/opt/az/lib/python3.10/site-packages
```

**Comment by wangzelin007** [comment]
The unofficial packages 2.0.81 and 2.18.0 on Ubuntu repo also contain bugs that make keyvault commands fail (https://github.com/Azure/azure-cli/issues/13101):

```
az keyvault secret show
```

Errors:

```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```
